# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Motorcycle Trips
author: Rex Guinn
author_link: https://rexguinn.net
author_description: I am a retired Unix system admin, have been using Linux since 1996 and enjoy traveling by Motorcycle or I did until recently, now we have a 2003 Audi ttr.
email: ragwing@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Motorcycle travelog showing some of our motorcycle trips over last 50 years.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rexguinn.github.io" 

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: eie2uzx

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
